### ISSUE TITLE
Specify which app to bring from background

### ISSUE THREAD

**Issue by Djihanegh** [X-SLAYER/bg_launcher#1]
Hello,

Is there a way to specify which app to bring from background by providing its android package name ?

Thank you.

**Comment by Djihanegh** [comment]
For anyone who needs this option,its available here : 

```
bg_launcher:
    git:
      url: https://github.com/Djihanegh/bg_launcher.git
      ref: main
```
